version: '3'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kenzchase-app
    restart: unless-stopped
    networks:
      - kenzchase-network

  nginx:
    image: nginx:alpine
    container_name: kenzchase-nginx
    ports:
      - "3000:80"  # Change the port if 3000 is already used by another service
    volumes:
      - ./nginx/kenzchase.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nextjs-app
    restart: unless-stopped
    networks:
      - kenzchase-network

networks:
  kenzchase-network:
    driver: bridge